Add note about `mpdecimal` requirement on some Unix platforms
eprbell/rp2 pull request #108
Opened 2024-03-20 04:54 UTC by antonok-edm

https://github.com/eprbell/rp2/issues/25#issuecomment-2008647693

`mpdecimal` can't really be added as a dependency of RP2 since it's a system library rather than a Python package, but at least we can document it in the installation/setup instructions.

2024-03-20 05:02 UTC, antonok-edm commented
Potentially, another option is to include a check like this during some initialization routine:
```python
try:
    from _decimal import *
except ImportError:
    print(MPDECIMAL_NOT_AVAILABLE_WARNING)
    sys.exit(-1)
```

2024-03-20 05:06 UTC, eprbell commented on README.dev.md
> +Note that [mpdecimal](https://www.bytereef.org/mpdecimal/) is required as a system dependency for RP2. Some platforms (e.g. Arch Linux) do not bundle mpdecimal with their official Python installation
Can we add mpdecimal to `install_requires` in `setup.cfg` instead?

2024-03-20 05:15 UTC, eprbell commented on README.dev.md
> +Note that [mpdecimal](https://www.bytereef.org/mpdecimal/) is required as a system dependency for RP2. Some platforms (e.g. Arch Linux) do not bundle mpdecimal with their official Python installation
Oh, I just realized you already answered while I was writing this comment.

2024-03-20 05:22 UTC, eprbell commented
> Potentially, another option is to include a check like this during some initialization routine:
> 
> ```python
> try:
>     from _decimal import *
> except ImportError:
>     print(MPDECIMAL_NOT_AVAILABLE_WARNING)
>     sys.exit(-1)
> ```

I think this is a good approach. It could go here: https://github.com/eprbell/rp2/blob/main/src/rp2/rp2_main.py#L70. The only changes needed are:
* use `LOGGER.error` instead of `print`;
* sys.exit(1) instead of -1;

Then I think we no longer need the changes to the README files.

2024-03-20 16:11 UTC, antonok-edm commented
updated!

2024-03-20 18:13 UTC, eprbell requested changes
LGTM! I just suggested a comment to describe the issue. Also I think it's fine to disable the import-outside-toplevel pylint warning on the line where it occurs.

2024-03-20 18:13 UTC, eprbell commented on src/rp2/rp2_main.py
> +    try:
```suggestion
    # On certain platforms the mpdecimal system library is missing (see details at: https://github.com/eprbell/rp2/issues/25).
    try:
```
Let's add a comment pointing to the discussion.

2024-03-21 00:09 UTC, eprbell approved these changes
Good stuff!

2024-03-21 00:09 UTC, merged