Jp plugin
eprbell/rp2 pull request #44
Opened 2022-06-16 00:05 UTC by macanudo527

Adding the JP Plugin to RP2.

2022-06-16 02:24 UTC, eprbell requested changes
Nice, first supported country after US!

2022-06-16 02:24 UTC, eprbell commented on src/rp2/plugin/country/jp.py
> +    # Measured in days
Maybe add a comment saying that JP has no long-term capital gains

2022-06-16 02:24 UTC, eprbell commented on src/rp2/plugin/country/jp.py
> +        return sys.maxsize
add `import sys` at the beginning

2022-06-16 02:24 UTC, eprbell commented on src/rp2/plugin/country/jp.py
> +    rp2_main(JP())
Add newline

2022-07-11 15:10 UTC, macanudo527 commented
These issues should be resolved now.

2022-07-14 23:41 UTC, eprbell approved these changes
LGTM!

2022-07-14 23:47 UTC, merged

2022-07-14 23:49 UTC, eprbell commented
BTW, you need to add a JP country plugin to DaLI as well: https://github.com/eprbell/dali-rp2/blob/main/README.dev.md#country-plugin-development